---
resolved_ips:
  192.168.44.101:
    names: [vitess-mgr01]
  192.168.44.102:
    names: [vitess-node01]
  192.168.44.103:
    names: [vitess-node02]
  192.168.44.104:
    names: [vitess-node03]

systemd_service_dir: "/lib/systemd/system"

etcd_initial_cluster_hosts: "{{ groups['etcd'] }}"
etcd_network_conf_key: /coreos.com/network/config 

flannel_network: "10.9.0.0/16"
