---
- name: Make working directory
  local_action:
    module: file
    path: "{{ cert_work_dir }}"
    state: directory
    mode: 0755
  run_once: true

- name: Put cert script
  local_action:
    module: template
    src: "{{ item }}.j2"
    dest: "{{ cert_work_dir }}/{{ item }}"
    mode: 0755
  with_items:
    - gen.sh
    - openssl.cnf
  run_once: true

- name: Run generate script
  local_action:
    module: command gen.sh chdir={{ cert_work_dir }}
  run_once: true
