---
- name: Put kube-dns resouce files
  template:
    src: "dns/{{ item }}.j2"
    dest: "{{ kube_manifest_dir }}/{{ item }}"
    owner: kube
    group: kube
  become: yes
  with_items: "{{ kube_addons_dns_resources }}"
  notify: Update dns resources

  # TODO: replace by kubectl module
- name: Present kube-dns resources
  kubectl:
    action: present
    filepath: "{{ kube_manifest_dir }}/{{ item }}"
  become: yes
  with_items: "{{ kube_addons_dns_resources }}"
