---
- name: Put kube-dns svc yml files
  template:
    src: dns/kube-dns-svc.yml.j2
    dest: "{{ kube_manifest_dir }}/kube-dns-svc.yml"
    owner: kube
    group: kube
  become: yes
  # TODO: replace by kubectl module
  # notify: 
  #   - Apply kube-dns 
  #
- name: Put kube-dns deploy yml files
  template:
    src: dns/kube-dns-controller.yml.j2
    dest: "{{ kube_manifest_dir }}/kube-dns-controller.yml"
    owner: kube
    group: kube
  become: yes
  # TODO: replace by kubectl module
  # notify: 
  #   - Apply kube-dns 

  # TODO: replace by kubectl module
- name: Apply kube-dns svc
  command: "kubectl create -f {{ kube_manifest_dir }}/kube-dns-svc.yml"
  become: yes

  # TODO: replace by kubectl module
- name: Apply kube-dns deploy
  command: "kubectl create -f {{ kube_manifest_dir }}/kube-dns-controller.yml"
  become: yes
