---

- name: Create flannel directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ flannel_subnet_dir }}"
    - "/opt/flannel-{{ flannel_version }}"
  become: yes

- name: Unarchive flannel package
  unarchive:
    src: "{{ flannel_pkg_url }}"
    dest: "/opt/flannel-{{ flannel_version }}"
    mode: 0755
    remote_src: True
  become: yes

- name: Create links of bins
  file:
    src: "/opt/flannel-{{ flannel_version }}/{{ item }}"
    path: "{{ flannel_bin_dir }}/{{ item }}"
    state: link
  with_items:
    - flanneld
    - mk-docker-opts.sh
  become: yes

- name: Setup flanneld service
  template:
    src: flanneld.service.j2
    dest: "{{ systemd_service_dir }}/flanneld.service"
    mode: 0755
  become: yes
  notify:
    - Reload systemd
    - Restart flanneld

- name: Enables flanneld service
  service: name=flanneld state=started enabled=yes
  become: yes

- name: Finishe handlers force
  meta: flush_handlers

- include: configure-network.yml
