---
- name: Create the kubelet working directory
  file:
    path: "{{ kubelet_working_dir }}"
    state: directory
    mode: 0755
  become: yes

- name: Put kube-apiserver config file
  template:
    src: kubelet.conf.j2
    dest: "{{ kube_conf_dir }}/kubelet.conf"
  become: yes
  notify: Restart kubelet

- name: Setup kubelet service
  template:
    src: kubelet.service.j2
    dest: "{{ systemd_service_dir }}/kubelet.service"
  become: yes
  notify:
    - Reload systemd
    - Restart kubelet

- name: Enable kubelet
  service: name=kubelet state=started enabled=yes
  become: yes
