---
- name: Install kube-proxy's dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - conntrack
  become: yes

- name: Setup kube-proxy service
  template:
    src: kube-proxy.service.j2
    dest: "{{ systemd_service_dir }}/kube-proxy.service"
  become: yes
  notify:
    - Reload systemd
    - Restart kube-proxy

- name: Enable kube-proxy
  service: name=kube-proxy state=started enabled=yes
  become: yes
