---
- name: Get iptables rules
  command: iptables -L --wait
  register: iptablesrules
  become: yes

- block:
  - name: Open apiserver port with iptables
    command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ kube_master_api_port }} -j ACCEPT -m comment --comment "kube-apiserver"
    become: yes

  - name: Save iptables rules
    command: invoke-rc.d netfilter-persistent save
    become: yes

  when: "'kube-apiserver' not in iptablesrules.stdout"
