---
- name: Put kube-apiserver config file
  template:
    src: apiserver.conf.j2
    dest: "{{ kube_conf_dir }}/apiserver.conf"
  become: yes
  notify: Restart kube-apiserver

- name: Setup kube-apiserver service
  template:
    src: kube-apiserver.service.j2
    dest: "{{ systemd_service_dir }}/kube-apiserver.service"
  become: yes
  notify:
    - Reload systemd
    - Restart kube-apiserver

- name: Enable kube-apiserver
  service: name=kube-apiserver state=started enabled=yes
  become: yes
