---
- name: Setup kube-controller-manager service
  template:
    src: kube-controller-manager.service.j2
    dest: "{{ systemd_service_dir }}/kube-controller-manager.service"
  become: yes
  notify:
    - Reload systemd
    - Restart kube-controller-manager

- name: Enable kube-controller-manager
  service: name=kube-controller-manager state=started enabled=yes
  become: yes
