---
- name: Create links of bins
  file:
    src: "{{ kube_pkg_dir }}/kubernetes/server/bin/{{ item }}"
    path: "{{ kube_bin_dir }}/{{ item }}"
    state: link
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl
  become: yes

- name: Put key file
  copy:
    src: server.key
    dest: "{{ kube_cert_dir }}/server.key"
    group: kube
    owner: kube
    mode: 0440
  become: yes

- include: kube-apiserver.yml
- include: kube-controller-manager.yml
- include: kube-scheduler.yml
- include: iptables.yml
